server:
  port: 8080
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: "jdbc:h2:mem:testdb"
    driverClassName: "org.h2.Driver"
    username: "sa"
    password: "passwordx"
    jpa:
      database-platform: "org.hibernate.dialect.H2Dialect"
      hibernate:
        ddl-auto: "create"
    h2:
      console:
        enabled: true
        path: "/h2-console"
---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: "condominio varanda nova america"
    driverClassName: "org.hibernate.dialect.MariaDBDialect"
    username: "root"
    password: "DDFXuZEUgjgiPLKahEOm2leE5ZduhVfoSYuzGJWtkFGprTM4WWoRp40hRbp2"
    jpa:
      database-platform: "org.hibernate.dialect.MariaDBDialect"
      hibernate:
        ddl-auto: "create"
    h2:
      console:
        enabled: true
        path: "/h2-console"