server:
  port: 8080

spring:
  profiles: test
  datasource:
    url: "jdbc:h2:mem:testdb"
    driverClassName: "org.h2.Driver"
    username: "sa"
    password: "passwordx"
    jpa:
      database-platform: "org.hibernate.dialect.H2Dialect"
      hibernate:
        ddl-auto: "create"
    h2:
      console:
        enabled: true
        path: "/h2-console"
---

spring:
  profiles: local
  datasource:
    url: "jdbc:mysql://localhost:3306/starbuckets?enabledTLSProtocols=TLSv1.2"
    username: "root"
    password: "DDFXuZEUgjgiPLKahEOm2leE5ZduhVfoSYuzGJWtkFGprTM4WWoRp40hRbp2"
    jpa:
      database-platform: "org.hibernate.dialect.MariaDBDialect"
      hibernate:
        ddl-auto: "create"
        user-new-id-generator-mappings: true


---