version: '3.3'
services:
  db:
    image: akoller/low-memory-mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'starbuckets'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'DDFXuZEUgjgiPLKahEOm2leE5ZduhVfoSYuzGJWtkFGprTM4WWoRp40hRbp2'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'DDFXuZEUgjgiPLKahEOm2leE5ZduhVfoSYuzGJWtkFGprTM4WWoRp40hRbp2'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./database/ajds:/var/lib/starbuckets/mysql